### ISSUE TITLE
typo3 version 7.5 UnknownObjectException

### ISSUE THREAD

**Issue by lmaylein** [subugoe/typo3-xmlinclude#3]
The following error message occurs when using Include XML with our typo3 v7.5 instance.
Could this be a configuration problem?

```
Wed, 28 Oct 2015 13:31:22 +0000 [ALERT] request="cb14266d55f8c" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20151028133121fdfeedfa - {"exception":"exception 'TYPO3\\CMS\\Extbase\\Object\\Container\\Exception\\UnknownObjectException' with message 'Could not analyse class:Subugoe\\Typo3-xmlinclude-7\\Controller\\IncludeController maybe not loaded or no autoloader?' in \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php:36\nStack trace:\n#0 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(334): TYPO3\\CMS\\Extbase\\Object\\Container\\ClassInfoFactory->buildClassInfoFromClassName('Subugoe\\\\Typo3-x...')\n#1 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(166): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getClassInfo('Subugoe\\\\Typo3-x...')\n#2 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/Container.php(121): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstanceInternal('Subugoe\\\\Typo3-x...', Array)\n#3 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Object\/ObjectManager.php(94): TYPO3\\CMS\\Extbase\\Object\\Container\\Container->getInstance('Subugoe\\\\Typo3-x...', Array)\n#4 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(109): TYPO3\\CMS\\Extbase\\Object\\ObjectManager->get('Subugoe\\\\Typo3-x...')\n#5 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Mvc\/Dispatcher.php(80): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->resolveController(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request))\n#6 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Mvc\/Web\/FrontendRequestHandler.php(66): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#7 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(197): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#8 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/extbase\/Classes\/Core\/Bootstrap.php(185): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#9 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#10 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(6992): call_user_func_array(Array, Array)\n#11 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/ContentObject\/UserContentObject.php(39): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#12 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(930): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#13 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/ContentObject\/ContentObjectRenderer.php(848): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#14 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3488): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#15 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3435): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#16 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/Controller\/TypoScriptFrontendController.php(3402): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#17 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/Http\/RequestHandler.php(230): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#18 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/core\/Classes\/Core\/Bootstrap.php(288): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 \/usr\/local\/typo3_src-7.5.0\/typo3\/sysext\/frontend\/Classes\/Http\/Application.php(76): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#20 \/usr\/local\/typo3_src-7.5.0\/index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#21 [internal function]: {closure}()\n#22 \/usr\/local\/typo3_src-7.5.0\/index.php(34): call_user_func(Object(Closure))\n#23 {main}"}
```

**Comment by lmaylein** [comment]
![typo3_xmlinclude_settings](https://cloud.githubusercontent.com/assets/7468155/10790517/0dab61ca-7d84-11e5-9a32-647dd5039d9f.png)

**Comment by ipf** [comment]
Sure. Just make sure your extension directory is named xmlinclude and not typo3-xmlinclude-7
